# Generated by Django 4.2 on 2025-05-29 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_variation_variation_category_reviewratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatings',
            new_name='ReviewRating',
        ),
    ]
