# Generated by Django 4.2 on 2025-06-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'productgalleries'},
        ),
    ]
